# Generated by Django 5.2.6 on 2025-10-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Предварительный просмотр",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("views_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["title", "creation_date"],
            },
        ),
    ]
